### ISSUE TITLE
After copying once, moving a block copies it again

### ISSUE THREAD

**Issue by laurensvalk** [mit-cml/workspace-multiselect#20]
In the first few seconds, everything works fine. After copying something though, it escalates quickly. 

This appears to be introduced in 0.1.7.

https://github.com/mit-cml/workspace-multiselect/assets/12326241/b40a2fd0-f510-4a38-9848-faf0fcf01f83

**Comment by HollowMan6** [comment]
I’ve already noticed that yesterday, and that looks like to be introduced as of the blockly version bump. I haven’t looked through what they have changed. A version downgrade should be a temporary workaround. https://github.com/mit-cml/workspace-multiselect/pull/19/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R47

**Comment by HollowMan6** [comment]
Looks like it should be their use of the new render management system in v10.1.x that caused this. https://github.com/google/blockly/pull/7307/files

Haven't figured out how to fix this still...

**Comment by HollowMan6** [comment]
It turned out to be an upstream issue: https://github.com/google/blockly/issues/7383

My suggestion is that, don't use Blockly version 10.1.x until that issue is fixed. It should be fine to keep the Blockly version as 10.1.1 here https://github.com/mit-cml/workspace-multiselect/blob/main/package.json#L47 We don't need to release again for downgrading as it's just a devDependency, the peerDependency is still Blockly v10.0.0, so users will face no issue when they integrate this plugin into their own project. If you want to develop this plugin, just downgrade the Blockly version in devDependencies to v10.0.2 manually.

We can close this issue for now and I will follow up on the upstream issue.

**Comment by HollowMan6** [comment]
I have submitted a PR to fix this in the upstream: https://github.com/google/blockly/pull/7384

**Comment by HollowMan6** [comment]
A new release has been made: https://github.com/google/blockly/releases/tag/blockly-v10.1.2

**Comment by laurensvalk** [comment]
Works great, thanks!
