### ISSUE TITLE
Suggestion for paste location

### ISSUE THREAD

**Issue by laurensvalk** [mit-cml/workspace-multiselect#28]
When copy pasting across tabs, the current behavior is (I think) to paste just next to old location.

In the another workspace (cross-tab), this may be far away, or even outside the view. This isn't always ideal.

Some ideas:
- When pasting with right-click, it seems most intuitive to paste wherever was right-clicked.
- When pasting with CTRL+V, perhaps the last clicked/mouseup location? In the same workspace, this is almost the same as the current behavior, because the last click is probably the completion of the selection. In the other worspace, this is likely at least within the view.

**Comment by HollowMan6** [comment]
That's an interesting idea, but what we are doing now is just following the official Blockly cross-tab-copy-paste plugin's behavior. I don't want to create any deviation with them as that might have unexpected side effects since after all, they have the whole picture.

If you manage to persuade them and after the change has already landed at the Blockly cross-tab-copy-paste plugin, I might consider applying the same changes here. Please consider opening the same issue at https://github.com/google/blockly-samples/issues for the cross-tab-copy-paste plugin, thanks!

**Comment by laurensvalk** [comment]
Sounds good. Thanks!
