### ISSUE TITLE
Fix the behavior of the application when shifting the mouse focus from an element that has a textarea

### ISSUE THREAD

**Issue by bbrudastyy** [mit-cml/workspace-multiselect#31]
Hi, when you shift the mouse focus from elements with textarea, the ability to print in the block disappears.
The code that has the error is in the multiselect file
<img width="696" alt="image" src="https://github.com/mit-cml/workspace-multiselect/assets/61388603/9b254373-5c77-4f71-a883-eb420f297b4d">

**Comment by HollowMan6** [comment]
This can be closed as #32 is now merged.

cc: @ewpatton @bbrudastyy

**Comment by xXBuilderBXx** [comment]
This still seems to be happening when the mouse cursor is outside of the textarea it loses the ability to type anything in it.

**Comment by HollowMan6** [comment]
@xXBuilderBXx The exception for `textarea` has already been added in: https://github.com/mit-cml/workspace-multiselect/pull/32/files#diff-35d1cc186954ac5abd5c842f9f470117a13383a3c83bbaccff0c82795da657f7R56 Are you now using the latest version (0.1.11)? If yes, could you please provide more information so that we can make more exceptions? (what's the node name of the element?)

**Comment by xXBuilderBXx** [comment]
This is working now, thought i had updated it properly on my end.
