### ISSUE TITLE
Upgrade `multiselect` plugin to use an IDragger (for Blockly 11)

### ISSUE THREAD

**Issue by HollowMan6** [mit-cml/workspace-multiselect#39]
Currently the multiselect plugin uses a custom block dragger to handle dragging multiple blocks at once. This is bad because it doesn’t allow you to select workspace comments as part of a multiselection. In Blockly 11, the upstream will make some changes to how the dragging in Blockly works. This would require some breaking changes, which would require fixes to the multi-select plugin. But after it's implemented we shouldn't have to monkey patch anymore! Which should make the plugin easier to maintain in the future.

### Custom Draggable

The multiselect plugin can implement a custom `IDraggable` that wraps all of the selected elements. It can delegate to drag operations to the individual elements.

```javascript
class MultiselectDraggable implements IDraggable {
  private subDraggables: IDraggable[];

  addSubDraggable() { /* Implementation */ }

  startDrag(e: PointerEvent) {
    for (const draggable of this.subDraggables) {
      draggable.startDrag(e);
    }
  }

  drag(newLoc: Coordinate, target: IDragTarget, e?: PointerEvent) {
    for (const draggable of this.subDraggables) {
      draggable.drag(Blockly.Coordinate.sum(newLoc, draggable.dragOffset), target, e);
    }
  }

  endDrag(e: PointerEvent) {
    for (const draggable of this.subDraggables) {
      draggable.endDrag(e);
    }
  }
}
```

This implementation also means that the multiselect plugin won’t have to do any special work to be compatible with the scroll options plugin, since the scroll options will override the `IDragger` while this creates a custom `IDraggable`.

### Selection

Currently, the multiselect plugin handles selection by passing a random one of the selected blocks to `Blockly.common.setSelected`. Instead, it will need to pass the `MultiselectDraggable` to `setSelected` so the `Gesture` can properly pass it to the `IDragger`.

Related issue: https://github.com/google/blockly-samples/issues/2317

**Comment by HollowMan6** [comment]
The beta version of v11 (v11.0.0-beta.8) has included the IDragger feature. Some docs to help with migration:

- Draggables: https://developers.google.com/blockly/guides/configure/web/dragging/draggable
This is the kind of object to implement to represent a multiselection.
- Draggers: https://developers.google.com/blockly/guides/configure/web/dragging/dragger
These handle calculating the workspace location where draggables should move to. We shouldn't need to implement one, but it might be useful to read this for context.
- Copy paste: https://developers.google.com/blockly/guides/configure/web/copy-paste
Since we'll be using a custom draggable, we'll need to handle copy-paste ourselves. We should be able to delegate to the pasters, so it shouldn't be too much lift.

**Comment by changminbark** [comment]
Hi everyone,

My name is Chang Min Bark and I will be the GSoC contributor in charge of upgrading the multiselect plugin. I am also in charge of cross-testing the mutliselect plugin with other Blockly plugins. I am looking forward to contributing to this community!

Thanks,
Chang Min

**Comment by changminbark** [comment]
Hello,

I made a few changes and wanted to test them out but when I run "npm start" it does not show anything. I do not even see the error messages. I ran the script without my changes and it also showed a blank white page (so I don't think it is a result of my changes). Is there something I can do to see the error messages?

Thanks,
Chang Min

**Comment by HollowMan6** [comment]
Copied from our last email, the **bold** and _italic_ part in the first entry answers your question. Also, check the screenshots, you need to use IDragger to replace that so we can fix and get the plugin working on Blockly v11.
> - Now the only difference between the blockly-v11 and the main is this commit https://github.com/mit-cml/workspace-multiselect/commit/11b76b8e651538f55c17e2743e6641ea14ee9f51, which is just a version change done by me to get you started. I haven’t done anything related to actual code for IDragger, **so that branch is actually still broken and you will see a blank page _with errors in the developer tools console_ (F12) once you do `npm start`. It will be your job to implement IDragger so that we can fix the Blockly v11 support.** You can start your implementation / fix guided by those errors as well as the documentation I mentioned in my first email/issue on GitHub https://github.com/mit-cml/workspace-multiselect/issues/39.
> - I don’t expect “@blockly/dev-tools” and any other possible conflict dependencies to explicitly indicate support for Blockly v11 now, as v11 is still in beta. But it looks fine to forcibly override that at this stage. Feel free to upgrade the version at any time later once you find they have the support.
> - You are allowed to do whatever you want at this stage in the codebase without the need to ask for permission (be bold and creative), as long as it doesn’t cause any regression. Once you submit the PR, I will review your code and let you know the best practice/alternative way if I find any problems, so relax and explore!
> - As another first step during the community bonding period, I would encourage you to try out the main branch as well to learn how things are supposed to work (since the blockly-v11 branch is broken, you won’t learn anything there). It will benefit you a lot after you finish the IDragger implementation to make sure no regression/bug is introduced, as well as for your second cross-testing task. A possible checklist at https://github.com/mit-cml/workspace-multiselect?tab=readme-ov-file#user-behavior or you might want to experience the features I mentioned in my talk last year https://github.com/HollowMan6/My-Google-Summer-of-Code/blob/main/Slide_Songlin_Multi-Select_Plugin_2023_Blockly_Summit.pptx

![image](https://github.com/mit-cml/workspace-multiselect/assets/43995067/e3ccd6a3-6a6d-498c-8f59-10249e2e7383)
![image](https://github.com/mit-cml/workspace-multiselect/assets/43995067/1e505ee7-5552-4b90-b64a-45a3c674801b)

**Comment by changminbark** [comment]
For the IDragger component, we would just need to import one without reimplementing it as the default one should work with the MultiselectDraggable that implements the IDraggable interface. Am I correct?

**Comment by HollowMan6** [comment]
Ah yes, sorry for the confusion I caused in my previous emails. I should call them `IDraggable`. Just correct them in my last comment.

**Comment by changminbark** [comment]
Hello,

I just had a question regarding the implementation of the IDraggable interface. Since the previous code was written in JavaScript and implementing an interface is a feature of TypeScript, should I write the code for the IDraggable implementation of the multi-select draggable in TypeScript? If so, do I have to install and configure the Webpack bundler for TypeScript?

**Comment by HollowMan6** [comment]
Good question! Yes, and if you feel like doing so, you can help convert the whole plugin into Typescript. I don't think you need to configure the Webpack bundler for TypeScript as the bundler is configured by `@blockly/dev-scripts` and it should already have the ability to handle Typescript, you can check one of the Typescript based plugin for reference https://github.com/google/blockly-samples/tree/master/plugins/block-dynamic-connection

**Comment by changminbark** [comment]
The main reason I asked is because when I tried importing the new class I created that implemented the IDraggable interface, I was encountering an error related to the code being in Typescript.

**Comment by HollowMan6** [comment]
I haven't investigated how to mix Javascript with Typescript in the Blockly plugin, you can check [block-dynamic-connection](https://github.com/google/blockly-samples/tree/master/plugins/block-dynamic-connection) to see how to use Typescript in the plugin. We can discuss it today later during the meeting if you can't get it fixed.

**Comment by changminbark** [comment]
After looking at the main branch (original one that you worked on), I am thinking of creating a typescript declared class called MultiDraggable that implements the IDraggable interface. Then, I was planning to create the MultiselectDraggable class that extends the MultiDraggable declared class that I created. The reason for this is that I cannot directly implement the IDraggable interface (typescript) in the MultiselectDraggable class (javascript). What do you think about this approach?

**Comment by HollowMan6** [comment]
Sounds good to me as long as it works. It's fine to use your approach if you find something that is not doable in Typescript, but I guess it's better to directly have MultiselectDraggable class implements the IDraggable interface in Typescript (so that we can skip MultiDraggable).

**Comment by changminbark** [comment]
I guess that if I want to skip the MultiDraggable, I would have to use some sort of tsc to compile the typescript into javascript. However, if I want to avoid that, I would have to go with my method. I will decide whether it would be better to use tsc or just use javascript as I start to develop this more.

I also have another question about the skeleton code that you provided in the original implementation description. In the "drag" method, you have a target parameter. However, the IDraggable interface does not have this, so the IDE is giving me an incompatible override message. What was your intention with this parameter? Was it to check whether the blocks being dragged can be connected to an existing block in the workspace?

**Comment by HollowMan6** [comment]
That code snippet was taken from the Blockly team's original design document, maybe later they found that unnecessary and removed that parameter in the beta version. Anyway, you can safely ignore that target parameter as now they don't have that.

**Comment by mark-friedman** [comment]
> I cannot directly implement the IDraggable interface (typescript) in the MultiselectDraggable class (javascript).

AFAIK, you should be able to just create a JavaScript class which satisfies the TypeScript interface and avoid using any TypeScript.   See, for example, [this](https://developers.google.com/blockly/guides/configure/web/dragging/draggable#implementation) section of the Blockly docs, which Songlin previously mentioned.  What issues were you seeing?

**Comment by mark-friedman** [comment]
The key, I think, is that you want your class to `extend` the Blockly interface.

**Comment by changminbark** [comment]
I have tried extending the Blockly interface but it does not allow me to extend an interface. That's why I thought that I needed to implement the interface to a MultiDraggable class (TypeScript) and then extend from that class (JavaScript). 

I also don't know why I cannot directly extend the IDraggable interface in the JavaScript file for MultiselectDraggable.

![image](https://github.com/mit-cml/workspace-multiselect/assets/88669927/f742592e-b1fd-40bd-a510-d678a2a8ff96)

**Comment by HollowMan6** [comment]
No worries, I think for the first step, we should get this working. Later we can consider refactoring and I will also see if there’s any way to avoid Typescript. At this stage I’m also not sure if there’s a better way.

**Comment by HollowMan6** [comment]
Or, you might want to try upgrading Blockly version https://www.npmjs.com/package/blockly/v/11.0.0-beta.12 Not sure if this can help improve things or not.

**Comment by HollowMan6** [comment]
Okay, looks like we still have the same error in 11.0.0-beta.12 as @changminbark mentioned.

<img width="801" alt="image" src="https://github.com/mit-cml/workspace-multiselect/assets/43995067/5853179a-2400-49a0-94f0-628bef7274a3">

**Comment by ewpatton** [comment]
You cannot extend a TypeScript interface in JavaScript because it doesn't exist. It is akin to type erasure in Java. The definition is used for type checking in TypeScript and then it is no longer needed at the JavaScript layer since JavaScript doesn't have the concept of an interface. It should be sufficient to write the JavaScript code to conform to the IDragger interface until we migrate the project over to typescript. Sent from my iPhoneOn May 15, 2024, at 19:29, Chang Min Bark ***@***.***> wrote:﻿
I have tried extending the Blockly interface but it does not allow me to extend an interface. That's why I thought that I needed to implement the interface to a MultiDraggable class (TypeScript) and then extend from that class (JavaScript).
I also don't know why I cannot directly extend the IDraggable interface in the JavaScript file for MultiselectDraggable.
image.png (view on web)

**Comment by changminbark** [comment]
Does that mean if I just create the class conforming to the IDraggable interface, there will be a default Dragger class that will handle dragging the created IDraggable class? I was looking through the Blockly-v11 files and found a Dragger class that implemented the IDragger interface, but it only had skeleton methods. Do I also have to create a class that implements the IDragger interface?

![image](https://github.com/mit-cml/workspace-multiselect/assets/88669927/927a7395-c25e-454c-b83f-d286b9160a5c)

**Comment by changminbark** [comment]
Okay, I was just a little concerned when looking into the IDragger interface and the Dragger class that implemented the interface. I will just assume that a Dragger class should handle it and continue to develop the MultiselectDraggable class.

**Comment by mark-friedman** [comment]
>... what it means by SVG root

From the description on the doc page that you quote from and the looking at the source of a few of the Blockly existing classes that implement the `IDraggable` interface (e.g. [block_svg.ts](https://github.com/google/blockly/blob/rc/v11.0.0/core/block_svg.ts) and [bubble.ts](https://github.com/google/blockly/blob/rc/v11.0.0/core/bubbles/bubble.ts)) it seems reasonably clear that `getSvgRoot()` needs to return the SVG of the thing that is getting dragged.  In this case the SVG of the multi-selected blocks.

**Comment by HollowMan6** [comment]
@changminbark Yes, Mark is right. I have already followed up on the related issue with Beka. Let's see how it goes.

**Comment by changminbark** [comment]
Okay, thank you!

**Comment by mark-friedman** [comment]
> Yes, Mark is right. I have already followed up on the related issue with Beka. Let's see how it goes.

Thanks for the email to Beka, @HollowMan6.  It wasn't clear to me either how to create or obtain that SVG.

**Comment by HollowMan6** [comment]
@changminbark So for MultiselectDraggable, we don't need to implement the `IRenderedElement` interface, which means no need for having the `getSvgRoot()` method.

**Comment by changminbark** [comment]
Okay, thank you!

**Comment by HollowMan6** [comment]
Blockly v11 is officially released! https://github.com/google/blockly/releases/tag/blockly-v11.0.0 Now we should work on the release version instead of the beta one, and I have done an upgrade of the dev dependencies that actually support v11 and forced pushed the commit to the blockly-v11 branch: https://github.com/mit-cml/workspace-multiselect/blob/blockly-v11/package.json#L45-L48 @changminbark

**Comment by changminbark** [comment]
Should I just manually update the dependencies? Currently, my branch is 4 commits ahead of the remote branch and 1 commit behind it.

![image](https://github.com/mit-cml/workspace-multiselect/assets/88669927/80c91088-69e7-4939-97f7-658f226ff845)

**Comment by changminbark** [comment]
I am also encountering an issue where I cannot seem to import the Coordinate class from Blockly after updating it. I am getting the following error message when I run the npm start script.

![image](https://github.com/mit-cml/workspace-multiselect/assets/88669927/57324458-013d-4cd4-899b-7758e4278042)

**Comment by changminbark** [comment]
Can the reason be because { Coordinate } is not exported in the blockly.d.ts file? Does this mean, it must be fixed on the Blockly side?

![image](https://github.com/mit-cml/workspace-multiselect/assets/88669927/3c75775c-251a-4ebc-a930-64993e151faf)

![image](https://github.com/mit-cml/workspace-multiselect/assets/88669927/5909aa6f-b99e-4979-ba38-abb06abdc27b)

**Comment by changminbark** [comment]
I think I fixed it by using Blockly.utils.Coordinate. I guess that I cannot directly import Coordinate but rather have to use it indirectly.

**Comment by HollowMan6** [comment]
> Should I just manually update the dependencies? Currently, my branch is 4 commits ahead of the remote branch and 1 commit behind it.

Sorry, I wasn't aware that you already have local commits. It can be a little complicated since I force-pushed. I guess you can drop these 2 commits to avoid conflict:
- https://github.com/changminbark/workspace-multiselect/commit/fb2c83534e5855943e8a6f9e4d54e0d827ec0971
- https://github.com/changminbark/workspace-multiselect/commit/11b76b8e651538f55c17e2743e6641ea14ee9f51

Then rebase on top of the upstream blockly-v11 branch.

> I think I fixed it by using Blockly.utils.Coordinate. I guess that I cannot directly import Coordinate but rather have to use it indirectly.

Great to know you fixed this by yourself!

**Comment by ewpatton** [comment]
Blockly provides a migration tool that helps with situations where they reorganize classes. You may want to run that on the plugin code to see if there is anything else that needs to be corrected. Sent from my iPhoneOn May 22, 2024, at 01:50, Hollow Man ***@***.***> wrote:﻿

Should I just manually update the dependencies? Currently, my branch is 4 commits ahead of the remote branch and 1 commit behind it.

Sorry, I wasn't aware that you already have local commits. It can be a little complicated since I force-pushed. I guess you can drop these 2 commits to avoid conflict:

***@***.***
***@***.***

Then rebase on top of the upstream blockly-v11 branch.

I think I fixed it by using Blockly.utils.Coordinate. I guess that I cannot directly import Coordinate but rather have to use it indirectly.

Great to know you fixed this by yourself!

**Comment by changminbark** [comment]
Hello @ewpatton ,

Thank you for the reply. How do I access this migration tool for Blockly? What I did was just copy over the updated dev-dependencies that Songlin made in the package.json file into my package.json file.

**Comment by mark-friedman** [comment]
> I think I fixed it by using Blockly.utils.Coordinate. I guess that I cannot directly import Coordinate but rather have to use it indirectly.

It's worth noting the following from thwe Blockly 11 release notes:
>
>If you install Blockly through npm, we now provide an exports clause to explicitly declare what you can import from our package.
>* Your build tooling may now throw an error if you deep import from our package such as import 'blockly/core/some/file/name.js', which has never been supported by Blockly but may have been made possible by your build tools.

**Comment by mark-friedman** [comment]
> Hello @ewpatton ,
> 
> Thank you for the reply. How do I access this migration tool for Blockly? What I did was just copy over the updated dev-dependencies that Songlin made in the package.json file into my package.json file.

Its [here](https://github.com/google/blockly-samples/tree/master/plugins/migration), though I'm not sure that it has been updated (yet) for Blockly 11.  It's worth trying, though.

**Comment by changminbark** [comment]
Hello,

May I ask what the purpose of Blockly.common.setSelected and Blockly.common.getSelected are? Are they mainly used for copying/pasting the selected block? 

![image](https://github.com/mit-cml/workspace-multiselect/assets/88669927/07b894f3-2404-4625-b9ff-e17ea9716fd9)

**Comment by changminbark** [comment]
On another note, I think I found a bug in the Multiselect plugin (original). This is footage of me testing it out on the original version of the plugin:


https://github.com/mit-cml/workspace-multiselect/assets/88669927/e43982b9-8bb8-4fb0-93a3-2e754d7151b8

**Comment by changminbark** [comment]
I am also encountering an issue where I select a group of blocks and then disable multiselect mode and then encounter an error where it is trying to run updateBlocks_ on the MultiselectDraggable object, which does not have a pathObject property, resulting in an error. However, the weird thing is that the code that calls the updateBlocks_ on the Blockly.getSelected should only run under these conditions:

// When not in multiple selection mode and Blockly selects a block not
// in currently selected set or unselects, clear the selected set.

However, I am not satisfying those conditions as I am merely disabling multiselect mode without unselecting the group of blocks.

![image](https://github.com/mit-cml/workspace-multiselect/assets/88669927/6df8c758-7eed-4a61-adb3-db20d79a25b7)

https://github.com/mit-cml/workspace-multiselect/assets/88669927/e00adaab-4a68-44d1-9a3e-13352511b571

updateBlocks_ is called here:

![image](https://github.com/mit-cml/workspace-multiselect/assets/88669927/f12a3ad2-12e0-46e0-bb59-5a2f79eedbf9)

**Comment by HollowMan6** [comment]
> On another note, I think I found a bug in the Multiselect plugin (original). I multi-deselect a group of blocks and then click at empty space, which seems to re-select the previously-selected group of blocks. This is footage of me testing it out on the original version of the plugin:

That's interesting, I don't remember clearly if this was done intentionally or not, but I think this can be a feature/behavior to document XD (Revert back to the initial selection state of entering the multi-selection mode when you click the empty workspace).

> I am also encountering an issue where I select a group of blocks and then disable multiselect mode and then encounter an error where it is trying to run updateBlocks_ on the MultiselectDraggable object, which does not have a pathObject property, resulting in an error. 

You can safely remove all the pathObject updateSelected thing, that was initially intended to make the block look like it's "selected", now all the selection is handled by the Dragger, and we don't need that anymore.

> However, the weird thing is that the code that calls the updateBlocks_ on the Blockly.getSelected should only run under these conditions:
> // When not in multiple selection mode and Blockly selects a block not
> // in currently selected set or unselects, clear the selected set.
> However, I am not satisfying those conditions as I am merely disabling multiselect mode without unselecting the group of blocks.

updateBlocks_ is also called by the DragSelect library element (un)selection event, so it might also be called when disabling multiselect mode without unselecting the group of blocks.
I think this should be fine previously, let me know if this is blocking you from doing something.

https://github.com/mit-cml/workspace-multiselect/blob/af7eeb41ea2774c6e58c39e4a186c2f37592dd7c/src/multiselect_controls.js#L402-L417

**Comment by changminbark** [comment]
> That's interesting, I don't remember clearly if this was done intentionally or not, but I think this can be a feature/behavior to document XD (Revert back to the initial selection state of entering the multi-selection mode when you click the empty workspace).

The weird thing about this is that it does not happen all the time. It only occurs in this scenario:
1. Turn on multiselect mode
2. Select a group of blocks
3. Turn off multiselect mode
4. Turn on multiselect mode
5. Unselect a group of blocks
6. Click on blank space to replicate weird behavior.


> You can safely remove all the pathObject updateSelected thing, that was initially intended to make the block look like it's "selected", now all the selection is handled by the Dragger, and we don't need that anymore.

I tried commenting these portions of the code out and it leads to the blocks not being highlighted during the multi-selection (though they are highlighted after I let go of the mouseclick) and another error:

![image](https://github.com/mit-cml/workspace-multiselect/assets/88669927/566b7337-6887-4032-b2f9-8d4e77a98c62)

**Comment by changminbark** [comment]
So I traced the error to the disableMultiselect() method. When I change the value of the Blockly.common.setSelected() in the pic to one of the random blocks in the selection, the error does not appear. 

![image](https://github.com/mit-cml/workspace-multiselect/assets/88669927/e7eaf641-5d5e-4f60-b102-129affcf8239)

This is probably because updateBlocks_(Blockly.getSelected()) is being called in the updateMultiselect() method right after. The thing that confuses me is why is updateMultiselect() being called when I am merely turning off the multiselect mode? Is it because multiselect makes it so that updateMultiselect() is called for any workspace event?

![image](https://github.com/mit-cml/workspace-multiselect/assets/88669927/de1ce7fc-7153-4da9-8d9d-a08a2c3c54c0)

![image](https://github.com/mit-cml/workspace-multiselect/assets/88669927/9178f34c-dd9f-4814-bb3b-fe875d3df066)

**Comment by HollowMan6** [comment]
About that bug, I guess we just miss some condition checks, feel free to fix that in your code

> I tried commenting these portions of the code out and it leads to the blocks not being highlighted during the multi-selection (though they are highlighted after I let go of the mouseclick) 

You might want to update the selection on the go in this case.

> and another error, which I think is because the multiselectDraggable class I made does not have a bringToFront() method:

Then feel free to do something, either comment out the code and handle the issue at a later stage to find a solution, or do type checks and only call that when it’s an actual block.

> Is it because multiselect makes it so that updateMultiselect() is called for any workspace event?

Ah yes, I do have some fix for fixing bugs in multi-workspace situations. Feel free to check old issues and PRs, such as https://github.com/mit-cml/workspace-multiselect/pull/24/files

**Comment by changminbark** [comment]
@HollowMan6 @mark-friedman 
Hello, so I finished implementing the multiple-workspace helper functions. However, I'm stuck with the drag functions for the multiselectDraggable. I think I have an idea about why the drag functions are not being called. Basically, there is no clickable interface/SVG for the multiselectDraggable, as I explained in my email to Beka. What suggestions do you have to fix this? Or should I just wait for Beka to respond?

Thank you!

**Comment by HollowMan6** [comment]
> Basically, there is no clickable interface/SVG for the multiselectDraggable, as I explained in my email to Beka. What suggestions do you have to fix this? Or should I just wait for Beka to respond?

We have already talked about this during our Saturday meeting, I'm not sure about the possible cause and I doubt if this is something really related to the SVG, since Beka has already mentioned that we don't need to implement the `IRenderedElement` interface in the previous email, but anyway it would be good to wait for Beka to respond.

> @changminbark So for MultiselectDraggable, we don't need to implement the `IRenderedElement` interface, which means no need for having the `getSvgRoot()` method.

**Comment by changminbark** [comment]
I am uploading here the email thread between Songlin, Beka, and me:

![image](https://github.com/mit-cml/workspace-multiselect/assets/88669927/507bbd24-c366-444c-bf75-343748368380)
![image](https://github.com/mit-cml/workspace-multiselect/assets/88669927/f9143bd7-65a9-464f-a914-eeba51d36582)
![image](https://github.com/mit-cml/workspace-multiselect/assets/88669927/477afeca-055b-44f5-9ba6-c1d9b0405f3a)
![image](https://github.com/mit-cml/workspace-multiselect/assets/88669927/2cc792b1-d2a6-4436-a0bf-8dd896e79dd2)
![image](https://github.com/mit-cml/workspace-multiselect/assets/88669927/abd12f3e-53c3-4878-b10f-ec5fadd95a8c)

This is for anyone who wants to learn more about the problem and what was proposed for the solution.

**Comment by HollowMan6** [comment]
> This is for anyone who wants to learn more about the problem and what was proposed for the solution.

Yes, you should also include this comment in the code, suggesting that we should remove this hacky workaround once the Blockly team has fixed this with their new flexible gesture handling system.

**Comment by HollowMan6** [comment]
> On another note, I think I found a bug in the Multiselect plugin (original). I multi-deselect a group of blocks and then click at empty space, which seems to re-select the previously-selected group of blocks. This is footage of me testing it out on the original version of the plugin:
> 
>  Multiselect_bug.mp4

**Comment by changminbark** [comment]
Hi everyone,

I finally got my laptop fixed and was able to resume implementing the multidraggable class. I am working on the final details of the implementation. More specifically, I am trying to fix this issue where the multidraggable object that contains the multiple blocks randomly jumps after starting a drag (after it has been moved before). How does the newLoc part of the drag function work? I think it has something to do with the coordinate. I also feel like the block disconnecting after being placed is related to this bug because when I reinitiate the drag, the blocks reconnect in the multidraggable object.

If anyone can give me suggestions as to how to implement the coordinates properly, that would be appreciated. For now, I will continue to explore different options and look into the drag strategy class.

![image](https://github.com/mit-cml/workspace-multiselect/assets/88669927/cb7b8498-f351-47f3-a447-e949f07635b3)

![image](https://github.com/mit-cml/workspace-multiselect/assets/88669927/04f11d8a-00d0-4e59-932c-53dfa991eb88)

![image](https://github.com/mit-cml/workspace-multiselect/assets/88669927/7d45f6d4-6699-45c0-925b-3f64ea101416)

![multidraggable_bug_coordinate](https://github.com/mit-cml/workspace-multiselect/assets/88669927/ba4623ee-ec74-476a-8b36-260879dc460d)

**Comment by changminbark** [comment]
Hi everyone,

I would like to write an update and say that I am 95% done with updating the plugin. The main issue where the blocks were disconnecting on the drag was that I made it so that every selected block was being dragged. After talking to Beka and Songlin, I made the necessary changes to make sure the drag methods were only being called in the topmost blocks in the selection. If anyone would like me to post the email thread, please comment below.

Now, I only have to test two test cases, which are:

![image](https://github.com/mit-cml/workspace-multiselect/assets/88669927/a01f6cd9-589a-4ff6-8b9e-e0f7ad3acdb6)

For the first test case, I think there may be an issue related to new updates in Blockly-v11. Correct me if I'm wrong, but there were updates to events in Blockly-v11 so that may not be compatible with the previous implementation of the multifield feature. In the code snippet below, my console.log is not firing, so I am guessing the new updates are not compatible with the e.element and e.recordUndo fields.

![image](https://github.com/mit-cml/workspace-multiselect/assets/88669927/4be3101e-c811-4139-a803-1d8499474a2a)

After implementing this and testing across two workspaces, I should be finished. All I would need to do is clean up the code and add comments/documentation, which should not take long. 

Thank you
